### PR TITLE
Add support for encoding type 27

### PR DESCRIPTION
**Pull request by 71**

### CODE REVIEW

**Comment by jiru** [comment]
Thank you for your contribution. Could you also add a test case for encoding type 27 in method `testDecryptMessage` in `kakaodecrypt.test.py`?

**Comment by 71** [comment]
I thought about adding a test case, but don't know how exactly. If I use one of the messages I decrypted myself, aren't I essentially leaking my friend's or my ID to the world?

Otherwise I could create a dummy test case [like this](https://github.com/jiru/kakaodecrypt/blob/master/kakaodecrypt.test.py#L41), but I wasn't sure it was good enough.

**Comment by jiru** [comment]
> If I use one of the messages I decrypted myself, aren't I essentially leaking my friend's or my ID to the world?

Yes. But that’s the only way we can be sure it’s working. I don’t know to what extent the ID is personal data or wether it can be used by a third party somehow, so it may or may not be a problem. It’s okay for me to merge your PR without a test case, but it would be better if you can add one. Maybe it’s possible to use a message of a well-known account like a translation bot?

**Comment by 71** [comment]
For now all the messages I have with encoding 27 are from real people, so I'd rather not leak that :/

**Pull request merged**
